### ISSUE TITLE
Elegant theme no longer uses tipue-search

### ISSUE THREAD

**Issue by nandac** [pelican-plugins/tipue-search#3]
@kdeldycke The elegant theme no longer uses tipue-search. They decided to move away from it because it was not maintained and now uses lunr.

Perhaps the README could be updated. I do not know about the Plumage theme.

**Comment by kdeldycke** [comment]
Thanks for the hint! Just removed the reference to Elegant theme.

As for Plumage, I'm the author of it. And yes, I'm still relying on Tipue Search for the time being. I plan to move from it at one point (see: https://github.com/kdeldycke/plumage/issues/49) but I have other priorities for now.

In the mean time, I plan to have `pelican-tipue-search` plugin released on PyPi (see: https://github.com/pelican-plugins/tipue-search/issues/2), as a kind of save-point before moving forward.

**Comment by dclong** [comment]
Does elegant still uses the tipue_search pelican plugin and only replaces the underlying tipue with lunr.js? Is configuration still the same?
